// <auto-generated />
using System;
using Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Datos.Migrations
{
    [DbContext(typeof(FidelizacionContext))]
    partial class FidelizacionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Dominio.Entidades.Compania", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoVencimientoId")
                        .HasColumnType("int");

                    b.Property<int>("VigenciaPuntos")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TipoVencimientoId");

                    b.ToTable("Compania");
                });

            modelBuilder.Entity("Dominio.Entidades.TipoVencimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipoVencimiento");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Tipo = "Tiempo"
                        },
                        new
                        {
                            Id = 2,
                            Tipo = "Conexion"
                        });
                });

            modelBuilder.Entity("Dominio.Entidades.Compania", b =>
                {
                    b.HasOne("Dominio.Entidades.TipoVencimiento", "TipoVencimiento")
                        .WithMany("Companias")
                        .HasForeignKey("TipoVencimientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoVencimiento");
                });

            modelBuilder.Entity("Dominio.Entidades.TipoVencimiento", b =>
                {
                    b.Navigation("Companias");
                });
#pragma warning restore 612, 618
        }
    }
}
